import SideBar from "@/Components/SideBar"
import "../styles/globals.css"


export const metadata = {
  title: 'Chat-GPT-Learn',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        
        <div className="flex">

          <div className="bg-[#202123] h-screen max-w-xs overflow-y-auto md:max-w-[20rem] w-full">
            <SideBar/> 

          </div>


          <div className="flex-1 bg-[#343541]">

            {children}

          </div>

        </div>
      
      </body>
    </html>
  )
}
